import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          GUÍA DE  <b>CONFIDENTES</b>
        </h1>

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}
<br/>
        <div className={styles.grid}>
          <a href="" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Makoto-Niijima.webp?w=1156&ssl=1"/>
          </a>

         <Link href="/haru">
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Haru-Okumura.webp?w=1106&ssl=1"/>
           
          </Link>

          <Link href="/yusuke">
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Yusuke-Kitawa.webp?w=1119&ssl=1"/>
           
          </Link>
          <Link href="/ann">
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Ann-Takamaki.webp?w=1104&ssl=1"/>
           
            </Link>
      <Link href="/sojiro">
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Sojiro-Sakura.webp?w=1156&ssl=1"/>
           
            </Link>
          <a href="" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Ryuji-Sakamoto.webp?w=1103&ssl=1"/>
           
          </a>
          <Link href="/akechi" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Goro-Akechi.webp?w=1105&ssl=1"/>
           
          </Link>
          <Link href="/futaba" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Futaba-Sakura.webp?w=1223&ssl=1"/>
           
          </Link>
          <Link href="/adivina" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Chihaya-Mifune.webp?w=1086&ssl=1"/>
           
            </Link>
          <Link href="/gemelas" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-guia-de-confidente-Caroline-y-Justine.webp?w=1104&ssl=1"/>
           
            </Link>
          <Link href="/iwai" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Iwai-Munehisa.webp?w=1104&ssl=1"/>
           
          </Link>
          <Link href="/maestra" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Sadayo-Kawakami.webp?w=1154&ssl=1"/>
           
          </Link>
          <Link href="/medica" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Tae-Takami.webp?w=1097&ssl=1"/>
           
            </Link>
          <Link href="/oya" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-guia-de-confidente-Ohya-Ichiko.webp?w=1105&ssl=1"/>
           
          </Link>
          <Link href="/togo" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Hifumi-Togo.webp?w=1085&ssl=1"/>
           
          </Link>
          <Link href="/orador" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Toranosuke-Yoshida.webp?w=1082&ssl=1"/>
           
          </Link>
          <Link href="/yoshizawa" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Kasumi-Yoshizawa.webp?w=1139&ssl=1"/>
           
          </Link>
          <Link href="/psicologo" >
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Takuto-Maruki.webp?w=1144&ssl=1"/>
           
            </Link>
         <Link href="/nino">
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Shinya-Oda.webp?w=1195&ssl=1"/>
           
            </Link>
            <Link href="/mishima">
            <img className={styles.card} src="https://i0.wp.com/www.solojugadores.com/wp-content/uploads/2022/11/Persona-5-Royal-guia-de-confidente-Yuuki-Mishima.webp?w=1084&ssl=1"/>
           
          </Link>

        
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' Pablo '}
          
        </a>
      </footer>
    </div>
  )
}
